---
title: "Lab: The 12 Days of Christmas"
output:
  prettydoc::html_pretty:
    theme: tactile
    highlight: github
    css: styles.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Packages for Functions
library(dplyr)
library(glue)
library(stringr)
library(purrr)
library(english)
```


```{r, include = FALSE}
xmas <- read.csv("https://www.dropbox.com/s/e584pryn8evm1gz/xmas.csv?dl=1")

```

---

## Step One:  Plurals

```{r}

pluralize_gift <- function(gift){
  
  if(str_detect(gift, "y")){
    gift <- str_replace(gift, "y", "ies")
  } else if(str_detect(gift, "oo")){
    gift <- str_replace(gift, "oo", "ee")
  } else {
    gift <- str_c(gift, "s")
  }

return(gift)

}

```

### Test pluralize_gift() Function

```{r}

purrr::map_chr(xmas$Gift.Item, pluralize_gift)

```


---

## Step Two: Creating sentences

```{r}
make_phrase <- function(num, num_word, item, verb, adjective, location) {
  
  verb <- str_replace_na(verb, "")
  adjective <- str_replace_na(adjective, "")
  location <- str_replace_na(location, "")
  
  vowel_start <- str_sub(item, 1, 1) %>% 
    str_detect("([aeiou])")
  
  if (num > 1) {
    
    item <- pluralize_gift(item)
    
  } else if (vowel_start) {
      item <- str_c("an ", item)

  } else {
    item <- str_c("a ", item)
    
  }
  
  glue::glue("{num_word} {adjective} {item} {verb} {location}") %>%
    str_squish()
  
}
```


### Test make_phrase() Function

```{r}
xmas <- xmas %>%
  mutate(day.num = as.character(as.english(Day)), 
    Full.Phrase = pmap_chr(list(num = Day, 
                                num_word = day.num, 
                                item = Gift.Item, 
                                verb = Verb, 
                                adjective = Adjective, 
                                location = Location), 
                           make_phrase)
  )

```


---


## Step Three:  Iteration.

```{r}

sing_line <- function(dataset, line, phrase_col){
  
  # Step 1: Setup the intro line
  
  num_word <- as.character(ordinal(line))
  
  intro <- glue::glue("On the {num_word} day of Christmas, my true love sent to me,")

  phrases <- dataset %>% 
      pull({{phrase_col}})

  phrase <- phrases[line:1] %>% 
    str_c(collapse = "\n")
  
  ## put it together
  
  return(glue::glue("{intro} \n{phrase}"))
}

```

### Test sing_line()

```{r}

sing_line(xmas, 
          line = 2, 
          phrase_col = Full.Phrase)

```

---

## Step Four: Use Your Functions!

```{r}
xmas2 <- xmas %>%
  mutate(
    day.num = as.character(english::english(Day)), 
    Full.Phrase = pmap_chr(list(num = Day, 
                                num_word = day.num, 
                                item = Gift.Item, 
                                verb = Verb, 
                                adjective = Adjective, 
                                location = Location), 
                           make_phrase)
  )

map_chr(1:12, ~sing_line(xmas2, .x, Full.Phrase)) %>%
  str_c(collapse = "\n") %>%
  cat()

```

## Step Five: Show Me Your Work! 

GitHub repository link: 

<br><br><br><br>


